name: Hlídač pozemků

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 7 * * *"

jobs:
  hlidac:
    runs-on: ubuntu-latest

    steps:
      - name: Stažení projektu
        uses: actions/checkout@v4

      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalace závislostí
        run: |
          pip install -r requirements.txt

      - name: Spuštění hlídače
        env:
          env:
          SMTP_HOST: smtp.gmail.com
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: |
          python src/main.py
